### ISSUE TITLE
Local lobby required for sv_cheats 1

### ISSUE THREAD

**Issue by Daar543** [fretmute/fretbots#11]
If trying to use the script from another server than from local server, an error after using `sv_cheats 1` occurs: "Change can be only made by the owner of the server" or something along the lines of that.

Could this be fixed, or at least added to the guide that you need to set up a local lobby?

**Comment by fretmute** [comment]
I don't believe that can be fixed; most of the methods under the hood that do things like give the bots gold are flagged by the engine as cheats and won't work unless sv_cheats is enabled. 

That said, the lobby host can tick the ENABLE CHEATS box in the lobby settings, and that should apply regardless of the server location (I suspect.  We always host locally, so I could be totally wrong here).  

Apologies for the late reply!

**Comment by Daar543** [comment]
If I understand, sv_cheats toggles the cheats which can be used by console, while "Enabled cheats" are the cheats in chat. I am not sure, how can I make a workaround. Guess I have to have a good computer and internet connection.

Anyway, if you still play this mode, could you figure that out? Thanks a lot.

**Comment by fretmute** [comment]
Since I'm doing github maintenance, I'll just close this. I feel there's nothing to be done about this.
