### ISSUE TITLE
When update?

### ISSUE THREAD

**Issue by Handsomepretty** [fretmute/fretbots#16]
Update when? There was new patch on 20 april that changed and added a lot of things. Would be good if this script will get an update. Thanks.

**Comment by fretmute** [comment]
Sorry, been busy with my real job, and reworking the neutral item methodology (spawning a new item from a list rather than juggling the best existing items) required a bunch of changes in my neutral item functions.  I'm testing my update now though.

**Comment by fretmute** [comment]
Update's been pushed.  It might be a little volatile.

**Comment by Handsomepretty** [comment]
Is there is an option to spawn neutral items for allied bots too like for enemies? Because they do not know how to use neutral item tokens and will equip neutral items which are owned by other heroes.

**Comment by fretmute** [comment]
Apologies for the late reply.  Allied bots are currently not supported at all; the whole thing is intended for five humans vs five bots.  Things get sort of wonky if you have less than a full complement of five people to begin with (i.e. the bots that don't have human counterparts get no bonuses). The only thing I do to allied bots currently is delete them from the bots table.

**Comment by Handsomepretty** [comment]
Actually it doesn´t matter if allied bots can get neutral items, after so many games not big of a problem, they still good expendables. XD.
