### ISSUE TITLE
Skywrath gets base magic resist from Shield of the Scion permanently when receiving bonuses

### ISSUE THREAD

**Issue by Zero-MF** [fretmute/fretbots#20]
I think there is a bug with Skywrath's Shield of the Scion and receiving magic resistance bonuses. He probably gets the base magic resist from the bonus intelligence from Shield of the Scion stacks permanently.

On difficulty 10 against Beginner AI bots he had 130% base magic resist towards the end of the game with Glimmer Cape and Pipe of Insight.

![Snímek obrazovky 2024-03-10 180053](https://github.com/fretmute/fretbots/assets/90244203/d3f03bf6-29ac-41f5-a8ff-e0adf203c142)

![Snímek obrazovky 2024-03-10 193054](https://github.com/fretmute/fretbots/assets/90244203/b2733171-0517-4631-a961-8f73449e9752)

**Comment by fretmute** [comment]
Although, now that I've thought about it more, it makes less sense, because these functions should be running while the bot in question is dead. I'll attempt to do some research.

**Comment by Zero-MF** [comment]
Either way the magic resistance bonus could be toned down a bit in my opinion. It makes magic damage quite weak in the late game. Especially when some bots already buy Glimmer and Pipe.

**Comment by fretmute** [comment]
That's already adjustable in SettingsDefault.lua, at least when things aren't going haywire.
```lua
-- caps for awards per game
awardCap =
{
	gold 				= 25000,
	armor 				= 25,
	magicResist 		= 25,
	levels 				= 10,
	neutral 			= 1200,
	stats 				= 25,
},
```

**Comment by fretmute** [comment]
Strange things are certainly afoot with `SetBaseMagicalResistanceValue`. 

![strangeness](https://github.com/fretmute/fretbots/assets/65498442/bb49433d-1cd6-4c57-9095-b2692204c8e1)

**Comment by fretmute** [comment]
Something is definitely wonky with `SetBaseMagicalResistanceValue`, and I didn't feel that working around it was worthwhile, so I've disabled Magic Resist awards by default in the current release.
