### ISSUE TITLE
NeutralItemFindTimer is using incorrect time

### ISSUE THREAD

**Issue by forest0xia** [fretmute/fretbots#7]
In NeutralItemFindTimer function, you set game time to be `Utilities:GetAbsoluteTime()`, but that's the time including negative time. So the setting `timings = {0, 420, 1020, 2020, 3600}` in your SettingsDefault will never be correctly applied.

**Comment by fretmute** [comment]
That is conceptually true, but NeutralItemFindTimer does not get created until the game enters DOTA_GAMERULES_STATE_GAME_IN_PROGRESS (at which point time is zero).  See BonusTimers:Initialize().

I wanted to prove to myself that I was not mistaken, so I instrumented by changing the function:

function BonusTimers:NeutralItemFindTimer()
  local gameTime = Utilities:GetAbsoluteTime()
  **print(gameTime)**

Output: 
0
1.033317565918
2.0333023071289
3.0332870483398

**Comment by forest0xia** [comment]
I won't even want to spend my time to find this bug if it was ever correctly applied. stop responding to my questions and thank you for your so late response.
