### ISSUE TITLE
Coding format

### ISSUE THREAD

**Issue by forest0xia** [fretmute/fretbots#8]
I'm not sure what is the text editor or IDE you are using for coding LUA. But how did you maintain those codes that the indentation is kind of totally messed up. 
Could you use a tool like https://goonlinetools.com/lua-beautifier/ to beautify the format, that could make it so much easier for yourself and others to view or upgrade the code.

**Comment by fretmute** [comment]
This is almost certainly an artifact of me always using UltraEdit with my own settings.  Everything's pretty for me, but I'll freely admit that I am internally inconsistent on tabs/spaces, which I assume makes things ugly unless your editor happens to have two space tabs.  I'll see what I can do on this front.
